#!/usr/bin/env sh

case $1 in
dev)
	compass watch --poll --environment development
	;;
release)
	compass compile --force --environment production
	git commit --all "Compiled for release"
	git push origin master:master
	git push origin master:gh-pages
	;;
*)
	echo "Usage: manage [command]"
	echo ""
	echo "Commands:"
	echo "  dev       Continuous non-compressing compilation"
	echo "  release   Compile compressed, commit, push and publish"
	echo ""
	echo "Dependencies: compass, git"
	;;
esac
